#' Load the x-spreadsheet javascript spreadsheet editor into Shiny
#'
#' This function creates an HTML widget to allow R Shiny to work with the
#' x-spreadsheet library (https://github.com/myliang/x-spreadsheet).
#'
#' The widget heavily relies on conversion between lists and json.
#'
#' To maintain the state of the spreadsheet editor one can store input$<example>_RXSpreadsheetData and load it again, see runExample().
#'
#'
#' @import htmlwidgets
#' @param data A list object that follows the x-spreadsheet format. This list object can be generated in two ways: use a list generated by input$<example>_RXSpreadsheetData or, to load existing data into the spreadsheet, convert a list of dataframes with dataFrameListToList.
#' @param options A list object that allows you to interact with the x-spreadsheet API directly, for all options check https://github.com/myliang/x-spreadsheet
#' @param elementId htmlwidget elementid
#' @export
RXSpreadsheet <- function(data, options = NULL, elementId = NULL) {

  # forward options using x
  message = list(
    data = data,
    options = options
  )

  # create widget
  htmlwidgets::createWidget(
    name = 'RXSpreadsheet',
    message,
    package = 'RXSpreadsheet',
    elementId = elementId
  )
}

#' Shiny bindings for RXSpreadsheet
#'
#' Output and render functions for using RXSpreadsheet within Shiny
#' applications and interactive Rmd documents.
#'
#' @param outputId output variable to read from
#' @param width,height Must be a valid CSS unit (like \code{'100\%'},
#'   \code{'400px'}, \code{'auto'}) or a number, which will be coerced to a
#'   string and have \code{'px'} appended.
#' @param expr An expression that generates a RXSpreadsheet
#' @param env The environment in which to evaluate \code{expr}.
#' @param quoted Is \code{expr} a quoted expression (with \code{quote()})? This
#'   is useful if you want to save an expression in a variable.
#'
#' @name RXSpreadsheet-shiny
#'
#' @export
RXSpreadsheetOutput <- function(outputId, width = '100%', height = '400px'){

  try({ shiny::removeInputHandler("rxspreadsheetlist") })
  shiny::registerInputHandler("rxspreadsheetlist", function(data, ...) {
    list(data)}, force = TRUE)

  htmlwidgets::shinyWidgetOutput(outputId, 'RXSpreadsheet', width, height, package = 'RXSpreadsheet')
}

#' @rdname RXSpreadsheet-shiny
#' @export
renderRXSpreadsheet <- function(expr, env = parent.frame(), quoted = FALSE) {
  if (!quoted) { expr <- substitute(expr) } # force quoted
  htmlwidgets::shinyRenderWidget(expr, RXSpreadsheetOutput, env, quoted = TRUE)
}
